sonar.projectKey=ImKrav_HomaraFrontend
sonar.organization=imkrav

sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.mts
sonar.exclusions=tests/**,**/*.test.*

sonar.javascript.lcov.reportPaths=coverage/lcov.info
